version: '3.4'
services:
  dshackle:
    container_name: dshackle
    image: emeraldpay/dshackle:0.12.0
    restart: unless-stopped
    volumes:
      - $PWD/eth:/etc/dshackle # This should hold all your yaml files
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - ALCHEMY_KEY=${ALCHEMY_KEY}
      - CHAINSTACK_NODE=${CHAINSTACK_NODE}
      - CHAINSTACK_USERNAME=${CHAINSTACK_USERNAME}
      - CHAINSTACK_PASSWORD=${CHAINSTACK_PASSWORD}
      - INFURA_KEY=${INFURA_KEY}
      - MORALIS_KEY=${MORALIS_KEY}
      - RIVET_KEY=${RIVET_KEY}
      - GETBLOCK_KEY=${GETBLOCK_KEY}
  dshackle_bsc:
    container_name: dshackle-bsc
    image: emeraldpay/dshackle:0.12.0
    restart: unless-stopped
    volumes:
      - $PWD/bsc:/etc/dshackle # This should hold all your yaml files
    ports:
      - "8081:8080"
      - "8083:8082"
  redis:
    container_name: redis
    image: healthcheck/redis:alpine
    restart: unless-stopped
    command: 
      - "redis-server"
      - "--maxmemory 1024M"
      - "--maxmemory-policy allkeys-lru"
      - '--save ""'

